{% set name = "unifunc" %}
{% set version = "1.3.5" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PedroMTQ/UniFunc/archive/refs/tags/{{ version }}.tar.gz
  sha256: 447a5f0cd8422d17d5f5694f2a6a1a9f483c674017b78e5a30bb8bbbe8a74bfc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - unifunc=unifunc.__main__:main

requirements:
  host:
    - setuptools >=42
    - wheel
    - pip
    - python >=3.7
  run:
    - nltk >=3.6
    - numpy
    - python >=3.7
    - requests

test:
  imports:
    - unifunc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PedroMTQ/UniFunc
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tool for similarity analysis of protein function annotations.
  description: |
    UniFunc is a text mining tool that processes and analysis text similarity
    between a pair of protein function annotations. It is mainly used as a
    cross-linking mechanism or redundancy elimination tool when processing
    annotations without any sort of database identifiers.
  dev_url: https://github.com/PedroMTQ/UniFunc

extra:
  recipe-maintainers:
    - PedroMTQ
